"""Regenerate src/lib/art/nastaliq-subsets.ts.

Calligraphy artwork is served as SVG images, which cannot load web fonts, so
each phrase embeds a tiny subset of Noto Nastaliq Urdu (SIL Open Font License)
containing only the glyphs that phrase needs.

    pip install fonttools brotli && python3 scripts/subset-nastaliq.py
"""
import base64, json, pathlib, subprocess, tempfile

PHRASES = {
    "iqbal": ("ستاروں سے آگے جہاں اور بھی ہیں", "There are worlds beyond the stars — Allama Iqbal"),
    "wahbayaan": ("واہ بیان", "Wahbayaan"),
    "noor": ("نور", "Noor — light"),
    "mohabbat": ("محبت", "Mohabbat — love"),
    "sabr": ("صبر", "Sabr — patience"),
    "hunar": ("ہنر", "Hunar — craft"),
    "umeed": ("امید", "Umeed — hope"),
    "khushamdeed": ("خوش آمدید", "Khush amdeed — welcome"),
}

root = pathlib.Path(__file__).resolve().parent.parent
font = root / "node_modules/@fontsource/noto-nastaliq-urdu/files/noto-nastaliq-urdu-arabic-700-normal.woff2"
out = {}
with tempfile.TemporaryDirectory() as tmp:
    for key, (text, meaning) in PHRASES.items():
        target = pathlib.Path(tmp) / f"{key}.woff2"
        subprocess.run(
            ["pyftsubset", str(font), f"--text={text}", "--layout-features=*", "--flavor=woff2", f"--output-file={target}"],
            check=True,
        )
        out[key] = {"text": text, "meaning": meaning, "font": base64.b64encode(target.read_bytes()).decode()}

lines = [
    "// Generated by scripts/subset-nastaliq.py — do not edit by hand.",
    "// Glyph subsets of Noto Nastaliq Urdu Bold (SIL Open Font License 1.1).",
    "export const NASTALIQ_PHRASES = " + json.dumps(out, ensure_ascii=False, indent=2) + " as const;",
    "",
    "export type NastaliqPhraseKey = keyof typeof NASTALIQ_PHRASES;",
    "",
]
(root / "src/lib/art/nastaliq-subsets.ts").write_text("\n".join(lines), encoding="utf-8")
print("wrote", len(out), "phrases")
