"""Regenerate src/components/store/hero/wordmark-typeface.ts.

The homepage hero renders the "Wahbayaan" wordmark as real 3D geometry
(drei <Text3D>), which needs a typeface.js font. This script instances
Fraunces (SIL Open Font License, already a dependency via @fontsource) at
the wordmark's settings and writes only the glyphs the word needs, so the
3D lettering is vector-sharp at any zoom and the data stays tiny.

    pip install fonttools brotli && python3 scripts/wordmark-typeface.py
"""
import json, pathlib
from fontTools.pens.recordingPen import RecordingPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "node_modules/@fontsource-variable/fraunces/files/fraunces-latin-full-normal.woff2"
OUT = ROOT / "src/components/store/hero/wordmark-typeface.ts"
TEXT = "Wahbayaan"
# Same feel as the 2D wordmark: soft, slightly wonky display cut, medium-bold.
AXES = {"opsz": 72, "wght": 560, "SOFT": 100, "WONK": 1}

font = instantiateVariableFont(TTFont(SRC), AXES)
glyph_set = font.getGlyphSet()
cmap = font.getBestCmap()
hmtx = font["hmtx"]


def fmt(v):
    r = round(v, 1)
    return str(int(r)) if r == int(r) else str(r)


def outline(name):
    pen = RecordingPen()
    glyph_set[name].draw(pen)
    out, xs = [], []
    for op, pts in pen.value:
        if op == "moveTo":
            (x, y), = pts
            out += ["m", fmt(x), fmt(y)]
            xs.append(x)
        elif op == "lineTo":
            (x, y), = pts
            out += ["l", fmt(x), fmt(y)]
            xs.append(x)
        elif op == "qCurveTo":
            # TrueType implied on-curve points between consecutive off-curve points.
            *offs, end = pts
            for i, c in enumerate(offs):
                if i < len(offs) - 1:
                    n = offs[i + 1]
                    e = ((c[0] + n[0]) / 2, (c[1] + n[1]) / 2)
                else:
                    e = end
                out += ["q", fmt(e[0]), fmt(e[1]), fmt(c[0]), fmt(c[1])]
                xs += [e[0], c[0]]
        elif op == "curveTo":
            (c1, c2, e) = pts
            out += ["b", fmt(e[0]), fmt(e[1]), fmt(c1[0]), fmt(c1[1]), fmt(c2[0]), fmt(c2[1])]
            xs += [e[0], c1[0], c2[0]]
        # closePath / endPath need no command in typeface.js
    return " ".join(out), (min(xs) if xs else 0), (max(xs) if xs else 0)


glyphs = {}
for ch in sorted(set(TEXT)):
    name = cmap[ord(ch)]
    o, x_min, x_max = outline(name)
    glyphs[ch] = {"ha": hmtx[name][0], "x_min": round(x_min), "x_max": round(x_max), "o": o}
glyphs[" "] = {"ha": hmtx[cmap[32]][0], "x_min": 0, "x_max": 0, "o": ""}

head, hhea, post = font["head"], font["hhea"], font["post"]
data = {
    "glyphs": glyphs,
    "familyName": "Fraunces Wordmark",
    "ascender": hhea.ascent,
    "descender": hhea.descent,
    "underlinePosition": post.underlinePosition,
    "underlineThickness": post.underlineThickness,
    "boundingBox": {"yMin": head.yMin, "xMin": head.xMin, "yMax": head.yMax, "xMax": head.xMax},
    "resolution": head.unitsPerEm,
    "original_font_information": {"format": 0, "fontFamily": "Fraunces", "license": "SIL Open Font License 1.1"},
    "cssFontWeight": "normal",
    "cssFontStyle": "normal",
}
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// Generated by scripts/wordmark-typeface.py — do not edit by hand.\n"
    f"// Fraunces (SIL OFL 1.1) instanced at {AXES}, glyphs for \"{TEXT}\" only.\n"
    f"export const wordmarkTypeface = {json.dumps(data, separators=(',', ':'))};\n"
)
print("wrote", OUT.relative_to(ROOT), OUT.stat().st_size, "bytes")
